name: Push to another repository

on:
  push:
    branches:
      - main

jobs:
  push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          repository: <username>/<repository>
          ref: <branch>
      - uses: actions/push@v2
        with:
          repository: <username>/<repository>
          branch: <branch>

