name: Push to rickthestig

on:
  push:
    branches:
      - main  # Adjust the branch name if needed

jobs:
  push-to-rickthestig:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Push to rickthestig
      run: |
        git config --global user.email "github-actions@example.com"
        git config --global user.name "Github Actions"
        git remote add rickthestig https://github.com/rickthestig/rickthestig.github.io.git  # Replace repository-name with your actual repository name
        git push rickthestig main  # Adjust the branch name if needed
      env:
        PAT: ${{ secrets.GH_PAT }}
