name: Push to rickthestig

on:
  push:
    branches:
      - main  # Adjust the branch name if needed
permissions:
  contents: write

jobs:
  push-to-rickthestig:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      with:
        token: ${{ secrets.GH_PAT }}

    - name: Push to rickthestig
      run: |
        git config --global user.email "github-actions@example.com"
        git config --global user.name "Github Actions"
        git remote add rickthestig https://github.com/rickthestig/Website.git  # Replace repository-name with your actual repository name
        git pull rickthestig main --rebase
        git push rickthestig pusher  # Adjust the branch name if needed
